set_property MARK_DEBUG true [get_nets system_i/memory_ctrl_merge_0_done_arm]
set_property MARK_DEBUG true [get_nets system_i/memory_ctrl_merge_0_done_arm2]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[8]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[9]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[12]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[13]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[11]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[14]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[0]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[2]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[4]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[6]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[7]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[1]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[3]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[5]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[10]}]
set_property MARK_DEBUG true [get_nets {system_i/memory_ctrl_merge_0_q[15]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[0]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[1]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[2]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[3]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[4]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_addr[5]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[1]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[2]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[8]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[10]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[12]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[7]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[14]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[15]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[0]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[4]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[6]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[9]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[13]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[3]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[5]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_d[11]}]
set_property MARK_DEBUG true [get_nets system_i/top_merge_0_en_memory]
set_property MARK_DEBUG true [get_nets system_i/top_merge_0_en_r]
set_property MARK_DEBUG true [get_nets system_i/top_merge_0_en_w]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_state[0]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_state[1]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_state[2]}]
set_property MARK_DEBUG true [get_nets {system_i/top_merge_0_state[3]}]
set_property MARK_DEBUG true [get_nets system_i/top_merge_0/done]
set_property MARK_DEBUG true [get_nets system_i/top_merge_0/done2]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/memory_ctrl_merge_0_q[0]} {system_i/memory_ctrl_merge_0_q[1]} {system_i/memory_ctrl_merge_0_q[2]} {system_i/memory_ctrl_merge_0_q[3]} {system_i/memory_ctrl_merge_0_q[4]} {system_i/memory_ctrl_merge_0_q[5]} {system_i/memory_ctrl_merge_0_q[6]} {system_i/memory_ctrl_merge_0_q[7]} {system_i/memory_ctrl_merge_0_q[8]} {system_i/memory_ctrl_merge_0_q[9]} {system_i/memory_ctrl_merge_0_q[10]} {system_i/memory_ctrl_merge_0_q[11]} {system_i/memory_ctrl_merge_0_q[12]} {system_i/memory_ctrl_merge_0_q[13]} {system_i/memory_ctrl_merge_0_q[14]} {system_i/memory_ctrl_merge_0_q[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/top_merge_0_state[0]} {system_i/top_merge_0_state[1]} {system_i/top_merge_0_state[2]} {system_i/top_merge_0_state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/top_merge_0_d[0]} {system_i/top_merge_0_d[1]} {system_i/top_merge_0_d[2]} {system_i/top_merge_0_d[3]} {system_i/top_merge_0_d[4]} {system_i/top_merge_0_d[5]} {system_i/top_merge_0_d[6]} {system_i/top_merge_0_d[7]} {system_i/top_merge_0_d[8]} {system_i/top_merge_0_d[9]} {system_i/top_merge_0_d[10]} {system_i/top_merge_0_d[11]} {system_i/top_merge_0_d[12]} {system_i/top_merge_0_d[13]} {system_i/top_merge_0_d[14]} {system_i/top_merge_0_d[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/top_merge_0_addr[0]} {system_i/top_merge_0_addr[1]} {system_i/top_merge_0_addr[2]} {system_i/top_merge_0_addr[3]} {system_i/top_merge_0_addr[4]} {system_i/top_merge_0_addr[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/top_merge_0/done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/top_merge_0/done2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/memory_ctrl_merge_0_done_arm]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/memory_ctrl_merge_0_done_arm2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list system_i/top_merge_0_en_memory]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list system_i/top_merge_0_en_r]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list system_i/top_merge_0_en_w]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
