# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Vivado/2018.2/final_merge_v1/final_merge_v1.srcs/sources_1/bd/system/ip/system_top_merge_0_0/system_top_merge_0_0.xci
# IP: The module: 'system_top_merge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/final_merge_v1/final_merge_v1.srcs/sources_1/bd/system/final_v1/xdc/IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_merge_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/Vivado/2018.2/final_merge_v1/final_merge_v1.srcs/sources_1/bd/system/ip/system_top_merge_0_0/system_top_merge_0_0.xci
# IP: The module: 'system_top_merge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Vivado/2018.2/final_merge_v1/final_merge_v1.srcs/sources_1/bd/system/final_v1/xdc/IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_merge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
